spring.beans.plugin:
  # Whether to enable adaptation
  enabled: false
  # The full-path name of the auto-assembled bean that needs to be culled from the spring container,
  # such as com.xxx.xxx, multiple separated by ","
  excludeAutoConfigurations: ""
  # The full path names of beans assembled with @Component annotations that need to be removed from the spring
  # container, such as com.xxxx.xxx, multiple separated by ","
  excludeBeans: ""
