# Configuration of Outlier Instance Removal Plugin
removal.config:
  # Expiration time of the instance call information. Unit: milliseconds
  expireTime: 60000
  # Exception for service call failure
  exceptions:
    - com.alibaba.dubbo.remoting.TimeoutException
    - org.apache.dubbo.remoting.TimeoutException
    - java.util.concurrent.TimeoutException
    - java.net.SocketTimeoutException
  # The outlier instance removal switch
  enableRemoval: false
  # The recovery time after the instance is removed
  recoveryTime: 30000
  # The size of the anomaly statistics window for outlier instances. Unit: milliseconds
  windowsTime: 1000
  # The number of anomalous statistics windows for outlier instances
  windowsNum: 10
  # Outlier instance removal rules，
  # scaleUpLimit：The proportion of outlier instances, that are removed from the upper limit。
  # minInstanceNum：Minimum number of instances。
  # key：Service name (valid for all services if default-rule)
  rules:
    - { key: default-rule, scaleUpLimit: 0.6, minInstanceNum: 1, errorRate: 0.6 }