name: Enhancement Tracking
description: Provide supporting details for a enhancement in development
labels: kind/enhancement
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be enhanced?
      description: |
        I want to enhance xxx.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
