loadbalancer.plugin:
  # dubbo load balancing policy
  # RANDOM(default), ROUNDROBIN, LEASTACTIVE, CONSISTENTHASH
  # SHORTESTRESPONSE，dubbo 2.7.7+
  dubboType: RANDOM
  # spring-cloud-loadbalancer load balancing policy
  # ROUND_ROBIN(default）, RANDOM，(spring cloud loadbalancer 2.2.7+)
  springType: ROUND_ROBIN
  # spring-cloud-netflix-ribbon load balancing policy
  # ZONE_AVOIDANCE(default）, RANDOM, ROUND_ROBIN, RETRY, BEST_AVAILABLE
  # AVAILABILITY_FILTERING, RESPONSE_TIME_WEIGHTED，Deprecated, WEIGHTED_RESPONSE_TIME
  ribbonType: ZONE_AVOIDANCE
