# configuration of traffic tag transmission between various channels(http/rpc/message queue etc.)
tag.transmission.config:
  # Whether to enable traffic tag transparent transmission. The default value is true
  enabled: true
  # Matching rules for keys of traffic tag that need to be transparent-transmitted.
  # Supports exact matching, prefix matching, and suffix matching
  matchRule:
    # the exact matching rule is in list form. If an element in the list is the same as the tag key,
    # it indicates that the tag needs to be transmitted, example values are ["id", "name"]
    exact: ["id", "name"]
    # the prefix matching rule is in in list form. If an element in the list is the prefix of a tag key,
    # it indicates that the tag needs to be transmitted, example values are ["x-sermant-"]
    prefix: ["x-sermant-"]
    # the suffix matching rule is in in list form. If an element in the list is the suffix of a tag key,
    # it indicates that the tag needs to be transmitted, example values are  ["-sermant"]
    suffix: ["-sermant"]

# configuration for transmitting tags across threads
crossthread.config:
  # Whether to transmit traffic tag when a new Thread is created. This parameter is enabled by default
  enabled-thread: true
  # Whether to transmit traffic tag when creating new thread tasks in a common thread pool.
  # This parameter is enabled by default
  enabled-thread-pool: true
  # Whether to transmit traffic tag when new thread tasks are created in the scheduled
  # thread pool. This parameter is enabled by default
  enabled-scheduler: true
