dynamic.config.plugin:
  enableCseAdapter: true # Whether to enable adaptation
  enableDynamicConfig: false # Whether to enable the dynamic configuration plugin
  enableOriginConfigCenter: false # Whether to enable the original configuration center. It is disabled by default
