# FlowControl configuration
flow.control.plugin:
  useCseRule: true # whether to configure cse rules
  enable-start-monitor: false # whether to enable indicator monitoring
  enable-system-adaptive: false # whether to enable system adaptive flow control
  enable-system-rule: false # whether to enable system rule flow control
