spring:
  application:
    name: sermant-injector

server:
  port: 8443
  ssl:
    enabled: true
    # ssl证书
    certificate: /home/config/sermant-injector.pem
    # ssl证书私钥
    certificate-private-key: /home/config/sermant-injector.key
    key-store-password: default
    key-alias: sermant-injector

sermant-agent:
  image:
    # agent镜像地址
    addr: xxx.huawei.com/sermant-agent:0.0.1
    # agent镜像拉取策略
    pullPolicy: IfNotPresent
  mount:
    # agent挂载磁盘
    path: /home/sermant-agent
  config:
    # agent配置中心类型: ZOOKEEPER/KIE
    type: ZOOKEEPER
    # agent配置中心地址
    address: http://localhost:2181
  service:
    # agent注册中心类型: SERVICE_COMB/NACOS
    type: SERVICE_COMB
    # agent注册中心地址
    address: http://localhost:30100
  # sermant-agent 配置环境变量的configMap的名字
  configMap: sermant-agent-env
  inject:
    # 当宿主应用已存在JAVA_TOOL_OPTIONS变量时，sermant的注入行为，before为在原变量前注入（默认），after为在原变量后注入，ignore为不注入
    action: before

management:
  endpoint:
    health:
      probes:
        enabled: true